Authorization with SSL certificates.
This CL introduces SSL certificate authorization between the client and server,
to stop all local clients from having access to all packet data stored by
stenotype.  To grant or revoke access to stenographer data, simply add or remove
a local user from the set of readers for client_key.pem.  *_cert.pem should be
readable by client and server, and server_key.pem only by the stenographer user.

This implements two-way verification... in 'readback' the client will verify the
server against the server's cert.  In the Go code, the server will verify the
client against the client's cert.

Certs are rewritten entirely on stenographer startup.  Otherwise, when you
remove someone's access to stenographer (remove them as a reader from
client_key.pem), if they've copied it somewhere they could still have access.
By rewriting completely, simply restarting stenographer fully removes access for
the removed user by invalidating any previous keys.

Note that in 'readback', we now use 'jq' to parse the json stenographer config,
since there's a couple of values we now need to read from there.  This is an
extra dependency which should be reflected in any packaging.

diff --git a/readback b/readback
--- a/readback
+++ b/readback
@@ -13,6 +13,10 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+if ! which jq >/dev/null; then
+  echo "Must install 'jq' for JSON parsing (apt-get install jq)"
+fi
+
 if [ "$#" -lt 1 ]; then
   cat 1>&2 <<EOF
 $0 provides a simple method for reading logs out of stenographer.
@@ -28,15 +32,33 @@ Examples:
  $0 'ip=1.1.1.1 ip=2.2.2.2' -w /tmp/out.pcap
 
 See README.md for more details on the Stenographer query language.
+
+Set the STENOGRAPHER_CONFIG environmental variable to point to your stenographer
+config if it's in a nonstandard place (defaults to /etc/stenographer/config).
 EOF
   exit 1
 fi
 
-PORT="${PORT-1234}"
+STENOGRAPHER_CONFIG="${STENOGRAPHER_CONFIG-/etc/stenographer/config}"
+PORT="$(cat "$STENOGRAPHER_CONFIG" | jq -r '.Port')"
+CERTPATH="$(cat "$STENOGRAPHER_CONFIG" | jq -r '.CertPath')"
+if [ -z "$PORT" -o -z "$CERTPATH" ]; then
+  echo "Unable to get port ($PORT) or certpath ($CERTPATH) from config ($STENOGRAPHER_CONFIG)" 1>&2
+  exit 1
+fi
 SERVER="localhost:$PORT"
 STENOQUERY="$1"
 shift
+echo "PORT=$PORT"
+echo "CERTPATH=$CERTPATH"
 
 echo "Running stenotype query '$STENOQUERY' against '$SERVER'" 1>&2
-curl -d "$STENOQUERY" "http://$SERVER/" 2>/dev/null |
+curl \
+    -d "$STENOQUERY" \
+    --cert "$CERTPATH/client_cert.pem" \
+    --key "$CERTPATH/client_key.pem" \
+    --cacert "$CERTPATH/server_cert.pem" \
+    --silent \
+    --show-error \
+    "https://$SERVER/" |
     tcpdump -r /dev/stdin -s 0 "$@"
